version: '3.9'
services:
  db:
    container_name: api-gateway-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-gateway
    ports:
      - '6003:5432'
    volumes:
      - pgdata1:/var/lib/postgresql/data

  api-gateway:
    container_name: api-gateway
    build: .
    restart: always
    volumes:
      - .:/app
    environment:
      DB_SCHEMA: api-gateway
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - '3000:3000'

volumes:
  pgdata1: {}

networks:
    default:
        external:
            name: ecommerce-build
